### ISSUE TITLE
Is it possible to the encrypted pass on a phone

### ISSUE THREAD

**Issue by minanagehsalalma** [Juvenal-Yescas/BruteForce-HOTSPOT-Mikrotik#3]
Let's say we managed to get the cookies with curl like app from story...what else is left ? Or there is somethimg that  i don't understand  !

**Comment by Juvenal-Yescas** [comment]
I don't understand your question well, what is the objective? @minanagehsalalma

**Comment by minanagehsalalma** [comment]
Sorry I meant to say 
"Is it possible to send the encrypted pass on a phone"

Just like bruteforcing but actually logging in using the correct user&pass...

I think just sending the login info will add the device Mac to the white list right ?

**Comment by Juvenal-Yescas** [comment]
That's right.

**Comment by minanagehsalalma** [comment]
> That's right.

What if I tried to login after another user with the same login info have already logged in ?

**Comment by Juvenal-Yescas** [comment]
ERROR = simultaneous session limit reached

 How many devices user can use with same account?
![alt text](https://i.ibb.co/fXjvtsr/users.png "Server Hotspot")

**Comment by minanagehsalalma** [comment]
> How many devices user can use with same account?

It's the default 1 for sure 


> ERROR = simultaneous session limit reached

Hmm. I see .. Does it happen by a chance that you have the logout button code (I mean the request that is sent after you click it) ?

**Comment by Juvenal-Yescas** [comment]
The 1 (shared users) is not default.
When you log out, the mac cookie is still registered.

**Comment by minanagehsalalma** [comment]
> When you log out, the mac cookie is still registered.

You mean that when a new Mac try to login with the same credentials after the original one logs out he still gets that error message !!

Is add Mac Cookie option is default ? For how long it's registered by default ?

**Comment by Juvenal-Yescas** [comment]
Mac registration is optional. It is registered as defined by the administrator.

**Comment by minanagehsalalma** [comment]
> Mac registration is optional. It is registered as defined by the administrator.

I know ... So the add Mac cookies should be turned off by default...

If Mac registration  wasn't defined by the admin then after the log out the other device should be able to log in with same credentials with no problem .. Right ?

**Comment by Juvenal-Yescas** [comment]
That's right.

**Comment by minanagehsalalma** [comment]
Is it possible to know if Mac registration or Mac cookies enabled without the admin panel ?

And 

> Does it happen by a chance that you have the logout button code (I mean the request that is sent after you click it) ?

You can get it from the network tab after you press F12 in chrome ... Then the logout button then copy the request as curl .. Only if you don't mind.

**Comment by minanagehsalalma** [comment]
I have found the logout page online but can't get the logout command from it !

**Comment by minanagehsalalma** [comment]
> When you log out, the mac cookie is still registered.

You were wrong 
"When user logs out mac cookie is removed in following cases:
user-request - user clicked on logout button.
admin-reset - disconnected from radius server or user is removed from hotspot active menu
nas-request - traffic limit reached
session-timeout"
