### ISSUE TITLE
Username or id only

### ISSUE THREAD

**Issue by KAMELCOLTD** [Juvenal-Yescas/BruteForce-HOTSPOT-Mikrotik#4]
as the subject i mean i have a mikrotik network that required only username to login there is only one box no passwords needed.
How can i make the app ignore the password section it always reading both users and password

if you can make one for users only it will be awesome

Thank you

**Comment by Juvenal-Yescas** [comment]
You can edit this line to ignore the password **passwordEncrypted** as an empty string or just delete it  https://github.com/Juvenal-Yescas/BruteForce-HOTSPOT-Mikrotik/blob/c6b173645d636748691d3b7777bee44bfbd241ad/hck-mikro.js#L64

@KAMELCOLTD

**Comment by KAMELCOLTD** [comment]
node mk1.js
5107597669--1
Could not use "nc", falling back to slower node.js method for sync requests.
/storage/emulated/0/python/k/mk1.js:26
    return $('script').get()[1].children[0].data;
                                           ^

TypeError: Cannot read property 'data' of undefined
    at makeRequest (/storage/emulated/0/python/k/mk1.js:26:44)
    at main (/storage/emulated/0/python/k/mk1.js:18:53)
    at Object.<anonymous> (/storage/emulated/0/python/k/mk1.js:10:9)
    at Module._compile (internal/modules/cjs/loader.js:958:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:994:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1046:10)
    at internal/main/run_main_module.js:17:11


always got this ? i just removed (passwordEncrypted)
'username='+user+'&'+'password='+'&dst=&popup=true'
This is the file

if you could edit the file for me maybe i did something wronge i tried many times editing from original file but same result.

**Comment by KAMELCOLTD** [comment]
i tried from pc and also from android .

**Comment by Juvenal-Yescas** [comment]
try with :

`body:'username='+user+'&'+'password=""&dst=&popup=true'`
 OR 
`body:'username='+user+'&'+'password='+user+'&dst=&popup=true'`

@KAMELCOLTD

**Comment by KAMELCOLTD** [comment]
`/storage/emulated/0/kas/hack/k.js:26
    return $('script').get()[1].children[0].data;
                                           ^

TypeError: Cannot read property 'data' of undefined
    at makeRequest (/storage/emulated/0/kas/hack/k.js:26:44)
    at main (/storage/emulated/0/kas/hack/k.js:18:53)
    at Object.<anonymous> (/storage/emulated/0/kas/hack/k.js:10:9)
    at Module._compile (internal/modules/cjs/loader.js:958:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:994:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1046:10)
    at internal/main/run_main_module.js:17:11`


same but new problem i will share the login page code maybe there is somthing deff

**Comment by KAMELCOLTD** [comment]
﻿
<!DOCTYPE html>
<html>
<head>
<title>ALNABEEL</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Modern Subscribe Form template Responsive, Login form web template,Flat Pricing tables,Flat Drop downs  Sign up Web Templates, Flat Web Templates, Login sign up Responsive web template, SmartPhone Compatible web template, free WebDesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>

<link href="css/style.css" rel="stylesheet" type="text/css" media="all" />



<style type="text/css">
.auto-style1 {
	direction: rtl;
}
.auto-style2 {
	text-align: center;
	color: #FFFFFF;
	font-size: x-large;
}
.auto-style3 {
	text-align: center;
	color: #FFFFFF;
}
  .auto-style15 {
	border: 0px solid #000000;
	direction: rtl;
}
.auto-style19 {
	color: black;
	background-color: #EECF80;
}

  </style>
  <style type="text/css">
  
  .auto-style33 {
	  border-style: solid;
	  border-width: 1px;
	  text-align: center;
	  font-size: large;
	  background-color: #368ED0;
  }

  .auto-style34 {
	  border-style: solid;
	  border-width: 1px;
	  text-align: center;
	  color: black;
	  background-color: #85B0D0;
  }

  .auto-style35 {
	  border-style: solid;
	  border-width: 1px;
	  text-align: center;
	  color: #303118;
	  background-color: #AECCE3;
  }

  .auto-style37 {
	  border-style: solid;
	  border-width: 1px;
	  text-align: center;
	  color: #303118;
	  background-color: #AECCE3;
	  font-size: large;
  }

  .auto-style38 {
	  text-align: center;
	  color: #FFFFFF;
	  font-size: large;
  }

  </style>
<script type="text/javascript" src="audio-player.js"></script>  

 <script>
function setCookie(cname,cvalue,exdays) {
    var d = new Date();
    d.setTime(d.getTime() + (exdays*10*1000));
    var expires = "expires=" + d.toGMTString();
	
    document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
}
function getCookie(cname) {
    var name = cname + "=";
    var decodedCookie = decodeURIComponent(document.cookie);
    var ca = decodedCookie.split(';');
    for(var i = 0; i < ca.length; i++) {
        var c = ca[i];
        while (c.charAt(0) == ' ') {
            c = c.substring(1);
        }
        if (c.indexOf(name) == 0) {
            return c.substring(name.length, c.length);
        }
    }
    return "";
}
function checkCookie() {
    var user=getCookie("username");
    if (user >= 5) {
        window.location = "block.html";
    } else {
	var counts;
	counts=Number(user);
	setCookie("username", counts+1, 30);
    }
}
</script>
<script type="text/javascript" src="/md5.js"></script>
	

	<script type='text/javascript' language="javascript">
	function rem(){
	var uname = document.getElementById('uname').value;
	var passw = document.getElementById('passw').value;
    var rem   = document.getElementById('remember').checked;
	if(rem == true){
    var date = new Date();
    date.setTime(date.getTime()+(5*1000));
    var expires = date.toGMTString();
    date.setTime(date.getTime()+(259200*1000));
    var expire  = date.toGMTString();
    document.cookie = 'uname='+uname+';expires='+expire+'';
	document.cookie = 'passw='+passw+';expires='+expire+'';
    document.cookie = 'error=1;expires='+expires+'';
    }
    else{
    return;
    }
	}
	function getCookie2(){
	var date = new Date();
    date.setTime(date.getTime()+(5*1000));
    var expires = date.toGMTString();
    var SP = document.cookie.split(';');
    for (i=0; i < SP.length; i++) {
    name_value = SP[i];
    str = name_value.substring(0,6);
    if(str.indexOf("uname") !== -1){
    uname = name_value.split('=');
    uname = uname[1];
    }
	if(str.indexOf("passw") !== -1){
    passw = name_value.split('=');
    passw = passw[1];
    }
	
    if(str.indexOf("error") !== -1){
    return;
    }
    }
    if(uname != ""){
    document.cookie = 'error=1;expires='+expires+'';
    window.location.href='login?username='+uname+'&password='+passw+'';
    }
    }
   getCookie2();
</script>
	<script type="text/javascript">
	
	</script>
</head>
<body>

	
	<div class="w3agileits-main">
		<h1>شبكة النبيل نت  اللاسلكية</h1>
		<div class="agileits-newsletter">
			<div class="w3ls-tabs"> 
				<h2>ALNABEEL</h2>
							 						 <marquee direction="right"><font color="#FFFFFF" size="5"> 
<span>مرحبا بكم في شبكه النبيل نت اللاسلكية ... تطوير مميزه ... وخدمات مميزه</span></font></marquee>
				<p>تسجيل الدخول </p>
				<form name="login" action="http://n.net/login" onSubmit="return doLogin()">
					<div class="auto-style1">
				<input type="hidden" name="dst" value=""/>
		        <input type="hidden" name="popup" value="true"/>
		         
					<input id='uname' type="tel" name="username" placeholder="رمز الدخول" >
					<input id="passw" type="hidden" name="password" placeholder="">
 حفظ بيانات الكرت
 <input checked id='remember' type='checkbox' name='remember'>
					<input type="submit" name="login" onclick='return rem();' value="دخول">
					</div>
					<div class="clearfix"> </div> 
					<div class="auto-style3">


						</div>

						</form>
			</div>	
		</div>	
	</div>	
			<div class="agileits-newsletter">
			<div class="w3ls-tabs"> 
				
				<h3 class="auto-style2">اسعار الكروت</h3>
                     <table cellpadding="2" class="auto-style15" style="width: 100%" align="center">
				<tr class="auto-style19">
					<td class="auto-style33">السعر</td>
					<td class="auto-style33">الوقت</td>
					<td class="auto-style33">التحميل</td>
					<td class="auto-style33">الصلاحية</td>
				</tr>
				
				<tr>
					<td class="auto-style34"><strong>100</strong></td>
					<td class="auto-style35"><strong>3 ساعات</strong></td>
					<td class="auto-style35"><strong>300 ميجا</strong></td>
					<td class="auto-style35"><strong>5 أيام</strong></td>
				</tr>
				<tr>
					<td class="auto-style34"><strong>200</strong></td>
					<td class="auto-style35"><strong>7 ساعات</strong></td>
					<td class="auto-style35"><strong>700 ميجا</strong></td>
					<td class="auto-style35"><strong>10 أيام</strong></td>
				</tr>
				<tr>
					<td class="auto-style34"><strong>300</strong></td>
					<td class="auto-style35"><strong>12 ساعة</strong></td>
					<td class="auto-style35"><strong>1200 ميجا</strong></td>
					<td class="auto-style35"><strong>15 يوم</strong></td>
				</tr>
				<tr>
					<td class="auto-style34"><strong>500</strong></td>
					<td class="auto-style35"><strong>22 ساعة</strong></td>
					<td class="auto-style35"><strong>2200 ميجا</strong></td>
					<td class="auto-style35"><strong>20 يوم</strong></td>
				</tr>
				<tr>
					<td class="auto-style34"><strong>1000</strong></td>
					<td class="auto-style35"><strong>50 ساعة</strong></td>
					<td class="auto-style35"><strong>4200 ميجا</strong></td>
					<td class="auto-style35"><strong>30 يوم</strong></td>
				</tr>
				<tr>
					<td class="auto-style34"><strong>2000</strong></td>
					<td class="auto-style35"><strong>أشتراك</strong></td>
					<td class="auto-style35"><strong>5 جيجا</strong></td>
					<td class="auto-style35"><strong>30 يوم</strong></td>
				</tr>
				<tr>
					<td class="auto-style34"><strong>3000</strong></td>
					<td class="auto-style35"><strong>أشتراك</strong></td>
					<td class="auto-style35"><strong>8 جيجا</strong></td>
					<td class="auto-style35"><strong>30 يوم</strong></td>
				</tr>
			</table>
				<h3 class="auto-style2">نقاط بيع الكروت</h3>
				<h4 class="auto-style37"> بقاله الربيع. دوام 24 ساعه . شارع 16 جوار مطعم الهلال </h4>
				<h4 class="auto-style37">مكتبه التيسير </h4>
				<h4 class="auto-style37"> بقاله الماجد قبال ثلاجه رزاز</h4>
				<h4 class="auto-style37"> مكتبه الفرسان - جوار مدرسه الاقصى</h4>
				<h4 class="auto-style37"> بقاله ركن الاقصى</h4>
				<h4 class="auto-style37"> بقاله الخير والبركه </h4>
				<h4 class="auto-style37"> بقالة ابو ياسر</h4>
				<h4 class="auto-style37"> بقاله البركه جوار مدرسه هايل</h4>
				<h4 class="auto-style37">مكتبه الوتاري </h4>
				<h4 class="auto-style37"> بقالة السنبله</h4>
				<h4 class="auto-style37"> بقاله زيدان</h4>
				<h4 class="auto-style37">بقاله امين الوتاري </h4>
				<h4 class="auto-style37"> بقاله معين</h4>
				<h4 class="auto-style37"> بقاله ابو علا </h4>
				<h4 class="auto-style37">بقاله الحبيشي </h4>
				<h4 class="auto-style37"> بقاله الشهره</h4>
				<h4 class="auto-style37"> بقاله المصباحي</h4>
				<h4 class="auto-style37"> بقاله الحمادي</h4>
				<h4 class="auto-style37"> بقاله الشعيبي</h4>
				<h4 class="auto-style37"> بقاله القباطي جوار مدرسه هايل</h4>
				<h4 class="auto-style37"> </h4>
			</div>	
	</div>	

						<p class="auto-style35">للتواصل والاستفسار الاتصال على الرقم : 775500321 - 737510386 </p>
	
	
	<div class="copyright agileinfo">
	<p class="txt-center"><a href="https://www.facebook.com/mikrotikman">
					<img alt="mikrotikman" title="المهندس عادل ماهر" src="images/mikro.png"></a></p>

	</div>
<script type="text/javascript">


</script>
	 
</body>
</html>

**Comment by Juvenal-Yescas** [comment]
Maybe the authentication is not using mikrotik, it would be necessary to completely review the login page. @KAMELCOLTD

**Comment by KAMELCOLTD** [comment]
this is the login.html page

**Comment by Juvenal-Yescas** [comment]
You only need a little modification to deal with *uname* and *passw*,  https://github.com/Juvenal-Yescas/BruteForce-HOTSPOT-Mikrotik/blob/c6b173645d636748691d3b7777bee44bfbd241ad/hck-mikro.js#L26
